
spring: 
  jpa: 
    hibernate: 
      ddl-auto: create-drop 
      properties: 
        dialect: org.hibernate.dialect.H2Dialect 
  datasource: 
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:file:~/test;USER=sa;PASSWORD=password 
    username: sa 
    password: password 
  h2: 
    console: 
      enabled: true

